### ISSUE TITLE
Cannot gererate recursions

### ISSUE THREAD

**Issue by masaomi-yamaguchi** [UChicago-PL/smyth#17]
I ran  
```./smyth forge examples/stutter_n.elm```
but it returned    
```No solutions.```
although it is the motivation example written in the overview of the paper.

I tried other examples, but synthesizer returned "No Solusionns" or wrong answer.

For example,
    ./smyth forge examples/max.elm
where max.elm is
```
type Nat
  = Z ()
  | S Nat

max : Nat -> Nat -> Nat
max m n =
  case m of
    Z _ ->
      n

    S m_ ->
      case n of
        Z _ ->
          m

        S n_ ->
          ??

assert max 1 1 == 1
assert max 4 3 == 4
assert max 3 5 == 5
```
returned
```No solutions```
although it is treated as can be handled in the paper.

It seems that it cannot generate a recursion directly because of a bug in the current implementation.

**Comment by masaomi-yamaguchi** [comment]
I used opam 2.0.5

**Comment by masaomi-yamaguchi** [comment]
Could you check whether it is a bug or my mistake of usage?

**Comment by justinlubin** [comment]
Hi Masaomi, thank you so much for catching this issue!

This bug appears to have been introduced in a very recent commit. I'll make sure this is fixed by the end of tomorrow.

In the meantime, I recommend running `git checkout c377816f94db797da64021dc4a2102410b34c5c0` to switch to a recent commit where the synthesizer works.

(For some reason, even on that commit, I'm getting a stack overflow exception on the `stutter_n.elm` example, but I'm running it on a completely different setup/computer than when I wrote the code, so for the harder problems it appears to be at least somewhat dependent on the environment.)

Thank you again! Let me know if I can help you work with Smyth in any other way.

**Comment by justinlubin** [comment]
I'll also note that the ["icfp-2020-v1" release](https://github.com/UChicago-PL/smyth/releases/tag/icfp-2020-v1) is essentially the most stable version of the code, as that release is exactly the code we used in our ICFP paper. (Commits since then might change some things.)

**Comment by justinlubin** [comment]
Hi @masaomi-yamaguchi, I think we fixed the issue! When you get a chance, could you take a look and see if the pull request that I just merged from @NiekM fixes it for you? Thanks again!

**Comment by justinlubin** [comment]
Since everything appears to be functional now, I'm going to close this issue, but please do let me know if there's anything else I can do to help out. Thanks!

**Comment by masaomi-yamaguchi** [comment]
I am sorry for my late reply.
Thank you so much!
It works well now!

**Comment by justinlubin** [comment]
No worries! :-) I'm glad it works for you now!
